### ISSUE TITLE
 infrared transmitter rate

### ISSUE THREAD

**Issue by mateusguilhermedasilva** [wennycooper/IR_receiver_rosserial_ircode#1]
Hello

could you tell me what rate the code "0x43" is sent by the transmitter? did you add a delay of how many milliseconds after irsend.sendRC5 on arduino?

Could you provide some constructive dimensions of the infrared receiver case?

thank you.

**Comment by wennycooper** [comment]
Hi,
I can't remember the delay time in the emitter side.
It could be 15ms or 31ms.. not for sure..  but I think you can try it for a better receiving rate.

For the infrared receiver case, you can check this:
https://github.com/wennycooper/Auto-Docking-Design

Kevin Kuei

**Comment by mateusguilhermedasilva** [comment]
thanks
